baseurl = "https://tech-blog.jameshsu.csie.org"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
theme = "terminal"
paginate = 5
title = "紙上得來終覺淺"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false
  customCss = ["css/custom.css"]

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.zh-tw]
    languageName = "中文"
    title = "紙上得來終覺淺"
    copyright = "jameshwc"
    menuMore = "查看更多"
    readMore = "查看更多"
    readOtherPosts = "看其他文章"
    [languages.zh-tw.params.logo]
      logoText = "紙上得來終覺淺"
      logoHomeLink = "/"
  
  [languages.en]
    languageName = "English"
    title = "Learn and Code"
    subtitle = "On the way"
    owner = "jameshwc"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

